-- init-h2.sql: create a citext domain so H2 accepts "citext" columnDefinition used in entities
CREATE DOMAIN IF NOT EXISTS citext AS VARCHAR;

-- Create dimension tables for analytics tests
CREATE TABLE IF NOT EXISTS dim_maquinista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo_maquinista BIGINT NOT NULL UNIQUE,
    nombre_completo VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dim_maquina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo_maquina VARCHAR(255) NOT NULL UNIQUE,
    nombre_maquina VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

-- Create fact_production table for analytics tests
CREATE TABLE IF NOT EXISTS fact_production (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha_contabilizacion DATE NOT NULL,
    maquina_fk BIGINT NOT NULL,
    maquinista_fk BIGINT,
    numero_log BIGINT NOT NULL,
    hora_contabilizacion TIME NOT NULL,
    fecha_notificacion DATE NOT NULL,
    documento BIGINT,
    material_sku BIGINT NOT NULL,
    material_descripcion VARCHAR(255),
    numero_pallet INTEGER,
    cantidad DECIMAL(18, 4) NOT NULL,
    peso_neto DECIMAL(18, 4) NOT NULL,
    lista VARCHAR(10),
    version_produccion VARCHAR(50),
    centro_costos BIGINT,
    turno VARCHAR(10) NOT NULL,
    jornada VARCHAR(10),
    usuario_sap VARCHAR(100),
    PRIMARY KEY (id),
    CONSTRAINT fk_fact_production_maquina FOREIGN KEY (maquina_fk) REFERENCES dim_maquina(id),
    CONSTRAINT fk_fact_production_maquinista FOREIGN KEY (maquinista_fk) REFERENCES dim_maquinista(id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_fact_production_fecha ON fact_production(fecha_contabilizacion);
CREATE INDEX IF NOT EXISTS idx_fact_production_maquina ON fact_production(maquina_fk);
CREATE INDEX IF NOT EXISTS idx_fact_production_maquinista ON fact_production(maquinista_fk);
CREATE INDEX IF NOT EXISTS idx_fact_production_turno ON fact_production(turno);

-- Create sequence for fact_production (H2 syntax)
CREATE SEQUENCE IF NOT EXISTS fact_production_id_seq START WITH 1 INCREMENT BY 100;
